### ISSUE TITLE
Clarify ambiguity in execution order of test cases

### ISSUE THREAD

**Issue by clevengr** [Kattis/problem-package-format#111] opened 2023-08-01 20:57 UTC
The current Problem Package Format specification says (at https://icpc.io/problem-package-format/spec/problem_package_format#test-data-groups):
```
At the top level, the test data is divided into exactly two groups: sample and secret.
Test files and groups will be used in lexicographical order on file base name. If a specific order is desired a numbered prefix such as 00, 01, 02, 03, and so on, can be used.
```
This is ambiguous.  It clearly says that test case execution order should be based on _file base name_.  On the other hand, it _seems_ to want to imply that the `sample` and `secret` _groups_ (directories) should also be considered in determining execution order.  However, a _directory name_ is _not_ part of the "file base name" of a file  (see for example [this definition of _basename_](https://en.wikipedia.org/wiki/Basename)) -- which leads to the ambiguity. 

For example, if a problem package contains the following beneath the `data` directory:
```
sample/first.{in,ans}
sample/second.{in,ans}
secret/bruteforce.{in,ans}
secret/quicksort.{in,ans}
```
then if the files are processed in lexicographic order _based on file base name_ then the execution order should be
```
bruteforce
first
quicksort
second
```
whereas if the intent is (for example) to process all "sample" files before processing any "secret" files, then the execution order should be
```
first
second
bruteforce
quicksort
```

The specification should be updated to clarify the intent.

Of course, this begs the question "what IS the intent?"   Should the spec _require_ that _all sample test cases be executed before any secret test cases_?   If so, then what does that do to the statement 
```
If a specific order is desired a numbered prefix such as 00, 01, 02, 03, and so on, can be used.
```
?   If the jury decides that it has a collection of test files and it wants them executed in a specific order and believes that the above statement means they can accomplish this by prepending a numeric order, that won't necessarily work if a CCS implementation still forces all "sample" files to be executed before any "secret" files.  So this presents an additional complication/ambiguity.

(This by the way is not simply an academic/pedantic exercise; we have a real question about how this should be handled in PC^2.  We'd _like_ to be spec-compliant -- but we can't comply with an ambiguous/conflicting spec.)

(Additional note:  there was at some (recent) point in time another statement elsewhere in the spec that said  
```
For pass-fail problems, the verdict of a submission is the first non-accepted verdict, where test cases are run in lexicographical order of their full file paths (note that sample comes before secret in this order).
```
This statement is cause for _further_  ambiguity, in that it refers to "full file paths", which clearly can be different from "file base name".  However, this statement has apparently now been removed from the spec (at least, I can't find it any more.)

**Comment by jsannemo** [comment] 2023-08-01 21:14
The correct intent is that all samples are judged before secret, i.e. considering the full paths of the test cases in lexicographic order.

The ambiguity in

> At the top level, the test data is divided into exactly two groups: sample and secret. Test files and groups will be used in lexicographical order on file base name. If a specific order is desired a numbered prefix such as 00, 01, 02, 03, and so on, can be used.

comes from considering groups (i.e. sample, secret) separately from cases. The paragraph was intended to mean "first, order the groups: sample < secret. Now judge each group in order, within which test files should be ordered". It's more convoluted than perhaps necessary because of how the non-ICPC parts of the spec look (which allow for many more test groups than only 2, and mixing cases and groups within a group).

Clarifying the spec is being actively worked on in the next revision.

**Comment by clevengr** [comment] 2023-08-01 21:46
So you're saying that there is general agreement that test cases in the sample directory should always be executed before any test cases in the secret directory?    I wonder whether different judge groups (in particular, the ICPC World Finals judges) are aware of (or necessarily agree with) that statement...

In any case, IMHO it's fine if that's the rule that the Problem Package Format is going to specify.  I would just like it to do so unambiguously... which I don't think it currently does.

**Comment by Tagl** [comment] 2023-08-01 22:18
In my experience that is the general agreement and a lot of confusion arose
for contestants when that was not the case.

What is the argument for not doing it that way?

**Comment by clevengr** [comment] 2023-08-01 22:27
I wasn't making any argument for doing it another way.  I'm saying that the existing specification is ambiguous about how it should be done.  In one place it mentions doing it in "full file path name" order, while in another place it mentions doing it in order of "file base name".  Those are inherently not (in general) going to produce the same order; therefore, the spec as written is ambiguous -- which leaves CCS implementers to ponder (and/or decide for themselves) what order to process the files.

I'd be fine with a spec which clearly and unambiguously states that "all test case files in the `sample` directory must be processed first, followed by all test case files in the `secret` directory, and within a given directory the files must be processed in lexicographic order of file base name".    I don't have a particular argument for doing it some other way (although someone else might); I just want the spec to state unambiguously what the proper order should be (which IMHO it does not currently do).

**Comment by RagnarGrootKoerkamp** [comment] 2023-08-01 22:48
Some comments:
- Let's first discuss intent. The lack of precise wording in the current spec is independent of that.
- In general, we should not put **any** requirement on the order things are run IMO. Testcases are independent, and do (MUST) not interfere with each other. So a judge should be allowed to run them in any order it thinks is useful. In particular both BAPCtools and DOMjudge parallelize.
- We should instead specify precisely how verdicts/scores are computed, and how that may/should depend on the order of testcases (where so far the convention/assumption for me has been 'order by path relative to `data/`)
- I don't see why samples should be run first. It really doesn't matter. What matters is
  a) teams get to see sample input as part of the statement and/or as download and/or some other way
  b) whether teams possibly get feedback (per-testcase verdict/score) and/or additional hints (`feedbackdir/team-feedback` or so). In DOMjudge this can be turned on or off, and when off, and also seems to be inconsistent between contests. We could spec this but it seems out-of-spec. So in that case, we even allow completely 'ignoring' that the samples are samples from a judging point of view and just using them similar to secret cases (for pass-fail at least; i don't know how sample interact with scoring typically).

**Comment by jsannemo** [comment] 2023-08-02 04:26
@RagnarGrootKoerkamp I do agree with you, but for ICPC WF (which I assume is the context John is interested in) this does actually matter, since systems must produce the same verdict for the shadowing setup to be maximally useful.

@clevengr there has been discussions on whether the wording on testcase ordering should live in the CCS specification instead, since this problem format is used in many more settings, for which some leaving the order of testcases undefined makes more sense, as evidenced by Ragnar's comment.

**Comment by jsannemo** [comment] 2023-08-02 04:36
@RagnarGrootKoerkamp you are of course right that judges can do whatever they want internally -- I think John is just interested in what externally observable behavior PC^2 should strive for, for an ICPC context.

> and how samples are accumulated into the final verdict.

But you agree that, at least according to the spec, this includes the final verdict being that of the first failed sample (if one did fail) by the rule:

> the convention/assumption for me has been 'order by path relative to data

that you mentioned?

**Comment by nickygerritsen** [comment] 2023-08-02 06:43
I do agree that the order to **run** things should not be specified explicitly, since indeed systems should be free to run things in any order.

I think a good approach would indeed be to say how the verdict is calculated and I do think first doing test groups in lexicographical order and then within a group the testcases in lexicographical order, then the first non-AC verdict makes sense. Not sure how we should write this down though.

Related, as currently in the spec and already quoted by John:

> Test files and groups will be used in lexicographical order on file base name.

`will be used` _for what_? I guess this is the part that we should improve, and/or maybe move to a different part that talks about grading/verdicts?

**Comment by niemela** [comment] 2023-08-02 12:04
> In one place it mentions doing it in "full file path name" order, while in another place it mentions doing it in order of "file base name". Those are inherently not (in general) going to produce the same order

This is not actually what the spec says. The key difference is that "Test files ***and groups*** will be used in lexicographical order". The test groups are exactly the directories, so taken together this means exactly the same thing as "full file path name order".

This is *very* unclear in the current "ICPC subset" documentation, since the explanations of test groups are not included. As @jsannemo said, clarifying the spec is being actively worked on.

**Comment by niemela** [comment] 2023-08-02 12:11
> I do agree that the order to **run** things should not be specified explicitly, since indeed systems should be free to run things in any order.

When the spec says that test cases should be run in a certain order, it is not intending to preclude speculatively running it in some other order or in parallel, but rather that the results MUST be AS IF the test cases were actually run in that order. I.e. the spec aims to define the *meaning* of a problem package, but not the internal implementation details of any system using problem packages.

**Comment by niemela** [comment] 2023-08-02 12:32
> * I don't see why samples should be run first. It really doesn't matter. What matters is
>       a) teams get to see sample input as part of the statement and/or as download and/or some other way
>       b) whether teams possibly get feedback (per-testcase verdict/score) and/or additional hints (`feedbackdir/team-feedback` or so). In DOMjudge this can be turned on or off, and when off, and also seems to be inconsistent between contests. We could spec this but it seems out-of-spec. So in that case, we even allow completely 'ignoring' that the samples are samples from a judging point of view and just using them similar to secret cases (for pass-fail at least; i don't know how sample interact with scoring typically).

You seem to be saying (please correct me if I'm misunderstanding?) that we should not require that samples are run (i.e. whether samples are considered part of the "official" test cases). 

Just like you say, I've seen it done both ways in contests. That said, every single time that it has mattered, i.e. when a submission that fails on sample is accepted, the judges have felt that this was a mistake. In the `legacy` version of the grader specification we had and `ignore_sample` setting, but we're (currently 😄) removing it from the new draft since it was not used much. In other words, I'm definitely leaning towards always requiring samples to be run (and run first), because that seems most useful.

What would be use case be to not do this?

**Comment by RagnarGrootKoerkamp** [comment] 2023-08-02 13:01
I think terminology is just much clearer if we specify the algorithm that computes the final verdict given the set of per-testcase verdicts.

E.g. for ICPC-style pass-fail:
* The final verdict is the first non-AC verdict over all testcases when sorted lexicographically by 'path', or AC when all testcases are AC.

(Where 'path' is specified to mean relative to `data` (although it doesn't actually matter), and `all` indeed includes the samples.)

Other than that, my main question is how samples affect scoring problems. Can you fail samples and get a score? From my point of view that seems most consistent with what is now chosen as defaults for grading.

**Comment by Tagl** [comment] 2023-08-02 13:06
> Other than that, my main question is how samples affect scoring problems. Can you fail samples and get a score? From my point of view that seems most consistent with what is now chosen as defaults for grading.

In scoring problems you can fail samples and still get a score. Often the samples are spread over different subtasks so you don't want to stop grading just because samples failed. However, I would say it is relatively common to include the samples within their respective subtasks to ensure that if you fail the sample, you fail the subtask it belongs to.

**Comment by niemela** [comment] 2023-09-18 00:52
I believe that we have agreement on what the spec should (and does) intend. We do need to work more on "wordsmithing" though. Closing this issue.

**Closed by niemela** 2023-09-18 00:52 UTC

**Comment by thorehusfeldt** [comment] 2023-09-18 09:36
Just for the record,

> What would be use case be to not do this?

As far as I know, all scoring problems “in the Swedish tradition” (which is used for IOI-style problems) have `ignore_sample`. However, the Swedish  _problem construction framework_ (a combination of `problemtools` and `kodsport/testdata_tools`) makes sure that every testcase in sample is included somewhere in secret.
